### ISSUE TITLE
Unable to install package using pip

### ISSUE THREAD

**Issue by apaleja** [vincentsarago/lambda-proxy#23]
Trying to install latest version of package using `pip install lambda-proxy==5.0.0`. getting below error:

```
Downloading https://files.pythonhosted.org/packages/c8/1e/2868a9b7e707304b9f8c00287f82c4a50336c4f68c87e60b39c931f9d50e/lambda-proxy-5.0.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\public\AppData\Local\Temp\pip-install-85dxf9ka\lambda-proxy\setup.py", line 6, in <module>
        readme = f.read()
      File "c:\users\public\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 518: character maps to <undefined>
``

Any idea what is the issue here ?

**Comment by vincentsarago** [comment]
thanks for the issue @apaleja, this seems to be a Windows problem, I'll look into this.

**Comment by vincentsarago** [comment]
@apaleja as mentioned in the error message, there is a decoding issue when setup.py is trying to `read()` the README.md.

can you please clone or download the repo and open the readme.md on your windows machine to see which characters it can't decode ?

**Comment by apaleja** [comment]
@vincentsarago Thanks for quick reply. here is the error I am getting when I am trying to install after clone:
```
ERROR: Command errored out with exit status 1:
     command: 'c:\users\public\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\sites\\lambda-proxy\\setup.py'"'"'; __file__='"'"'C:\\sites\\lambda-proxy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: C:\sites\lambda-proxy\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\sites\lambda-proxy\setup.py", line 6, in <module>
        readme = f.read()
      File "c:\users\public\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 526: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by apaleja** [comment]
@vincentsarago Any pointers how to solve this ?

**Comment by vincentsarago** [comment]
@apaleja thanks for the ping, I just release version 5.0.1, I hope it will fix your problem. Please let me know if it don't !

**Comment by apaleja** [comment]
@vincentsarago Thank you very much. I can confirm, I am able to install it now.
